<?php

namespace Tests\Feature;

use App\Models\Article;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

class ArticleTest extends TestCase
{
    use RefreshDatabase;

    private function published(array $overrides = []): Article
    {
        return Article::query()->create(array_merge([
            'slug' => 'advantages-of-social-media',
            'title_en' => 'Advantages of social media',
            'title_ar' => 'فوائد وسائل التواصل الاجتماعي',
            'body_en' => '<h2>Advantages</h2><p>Reach more people.</p>',
            'body_ar' => '<h2>الفوائد</h2><p>الوصول إلى جمهور أكبر.</p>',
            'is_published' => true,
            'published_at' => now(),
        ], $overrides));
    }

    public function test_public_articles_list_returns_only_published(): void
    {
        $this->published();
        $this->published([
            'slug' => 'draft-article',
            'title_en' => 'Draft article',
            'is_published' => false,
            'published_at' => null,
        ]);

        $this->getJson('/api/articles')
            ->assertOk()
            ->assertJsonCount(1, 'data')
            ->assertJsonPath('data.0.title_en', 'Advantages of social media');
    }

    public function test_public_article_show_by_slug_returns_html_body(): void
    {
        $this->published();

        $this->getJson('/api/articles/advantages-of-social-media')
            ->assertOk()
            ->assertJsonPath('data.slug', 'advantages-of-social-media')
            ->assertJsonPath('data.body_en', '<h2>Advantages</h2><p>Reach more people.</p>');
    }

    public function test_public_article_show_hides_unpublished(): void
    {
        $this->published([
            'slug' => 'hidden',
            'is_published' => false,
            'published_at' => null,
        ]);

        $this->getJson('/api/articles/hidden')->assertNotFound();
    }

    public function test_guest_cannot_create_article(): void
    {
        $this->postJson('/api/admin/articles', [
            'title_en' => 'X',
            'title_ar' => 'X',
            'body_en' => '<p>X</p>',
            'body_ar' => '<p>X</p>',
        ])->assertUnauthorized();
    }

    public function test_admin_can_create_article_with_autogenerated_slug(): void
    {
        Sanctum::actingAs(User::factory()->create(['is_admin' => true]));

        $this->postJson('/api/admin/articles', [
            'title_en' => 'Why video content wins',
            'title_ar' => 'لماذا ينجح محتوى الفيديو',
            'body_en' => '<h2>Video</h2><p>It drives <strong>engagement</strong>.</p>',
            'body_ar' => '<h2>فيديو</h2><p>يعزّز التفاعل.</p>',
        ])->assertCreated()
            ->assertJsonPath('data.slug', 'why-video-content-wins')
            ->assertJsonPath('data.body_en', '<h2>Video</h2><p>It drives <strong>engagement</strong>.</p>')
            ->assertJsonPath('data.is_published', true);

        $this->assertNotNull(Article::query()->first()?->published_at);
    }

    public function test_admin_create_deduplicates_slug(): void
    {
        Sanctum::actingAs(User::factory()->create(['is_admin' => true]));

        $payload = [
            'title_en' => 'Advantages of social media',
            'title_ar' => 'فوائد',
            'body_en' => '<p>One</p>',
            'body_ar' => '<p>واحد</p>',
        ];

        $this->postJson('/api/admin/articles', $payload)->assertCreated()->assertJsonPath('data.slug', 'advantages-of-social-media');
        $this->postJson('/api/admin/articles', $payload)->assertCreated()->assertJsonPath('data.slug', 'advantages-of-social-media-2');
    }

    public function test_store_requires_title_and_body(): void
    {
        Sanctum::actingAs(User::factory()->create(['is_admin' => true]));

        $this->postJson('/api/admin/articles', [])
            ->assertUnprocessable()
            ->assertJsonValidationErrors(['title_en', 'title_ar', 'body_en', 'body_ar']);
    }

    public function test_admin_can_update_and_unpublish_article(): void
    {
        Sanctum::actingAs(User::factory()->create(['is_admin' => true]));
        $article = $this->published();

        $this->putJson("/api/admin/articles/{$article->id}", [
            'title_en' => 'Advantages of social media in 2026',
            'is_published' => false,
        ])->assertOk()
            ->assertJsonPath('data.title_en', 'Advantages of social media in 2026')
            ->assertJsonPath('data.is_published', false);

        $this->getJson('/api/articles')->assertOk()->assertJsonCount(0, 'data');
    }

    public function test_admin_can_delete_article(): void
    {
        Sanctum::actingAs(User::factory()->create(['is_admin' => true]));
        $article = $this->published();

        $this->deleteJson("/api/admin/articles/{$article->id}")
            ->assertOk()
            ->assertJsonPath('message', 'Deleted.');

        $this->assertDatabaseMissing('articles', ['id' => $article->id]);
    }
}
