import type { Translations } from "@docx-editor.dev/i18n";

/**
 * Arabic labels for the Word editor chrome. The editor ships no Arabic catalogue; keys left out
 * here fall back to English. Keep this a module constant so the editor memoizes it.
 */
export const editorArabic: Translations = {
  _lang: "ar",
  common: { cancel: "إلغاء", apply: "تطبيق", close: "إغلاق", comment: "تعليق", dismiss: "إخفاء" },
  toolbar: {
    ariaLabel: "شريط التنسيق",
    file: "ملف",
    format: "تنسيق",
    insert: "إدراج",
    review: "مراجعة",
    open: "فتح ملف Word",
    save: "حفظ",
    print: "طباعة",
    pageSetup: "إعداد الصفحة",
    leftToRight: "نص من اليسار لليمين",
    rightToLeft: "نص من اليمين لليسار",
    image: "صورة",
    table: "جدول",
    insertTable: "إدراج جدول",
    break: "فاصل",
    insertFootnote: "إدراج حاشية سفلية",
    insertEndnote: "إدراج تعليق ختامي",
    pageBreak: "فاصل صفحة",
    sectionBreakNextPage: "فاصل قسم (صفحة تالية)",
    sectionBreakContinuous: "فاصل قسم (متصل)",
    tableOfContents: "جدول المحتويات",
    watermark: "علامة مائية",
    help: "مساعدة",
    export: "تصدير",
    exportPdf: "PDF (.pdf)",
    exportFailed: "فشل التصدير: {message}",
    exportingPdf: "جارٍ تجهيز PDF…",
    exportPdfFailed: "فشل تصدير PDF",
    exportDownloadHint: "يبدأ التنزيل عندما يجهز الملف. يمكنك متابعة التحرير.",
    exportContinueEditing: "متابعة التحرير",
    printPreparing: "جارٍ التحضير للطباعة…",
    printOpenPdf: "فتح PDF",
    printFailed: "فشلت الطباعة",
    printFailedMessage: "فشلت الطباعة: {message}",
    printLoadFailed: "لم يُحمَّل ملف PDF للطباعة. اختر «فتح PDF» ثم اطبع من العارض.",
    printRefused: "المتصفح منع الطباعة من الصفحة. اختر «فتح PDF» ثم اطبع من العارض.",
    printNoViewer: "هذا المتصفح لا يطبع PDF من الصفحة. اختر «فتح PDF» ثم اطبع من العارض.",
  },
  formattingBar: {
    label: "أدوات التنسيق",
    groups: {
      history: "السجل",
      zoom: "التكبير",
      styles: "الأنماط",
      font: "الخط",
      textFormatting: "تنسيق النص",
      script: "كتابة مرتفعة ومنخفضة",
      alignment: "المحاذاة",
      listFormatting: "القوائم",
      format: "تنسيق",
      image: "صورة",
      table: "جدول",
    },
    undo: "تراجع",
    undoShortcut: "تراجع (Ctrl+Z)",
    redo: "إعادة",
    redoShortcut: "إعادة (Ctrl+Y)",
    bold: "عريض",
    boldShortcut: "عريض (Ctrl+B)",
    italic: "مائل",
    italicShortcut: "مائل (Ctrl+I)",
    underline: "تسطير",
    underlineShortcut: "تسطير (Ctrl+U)",
    strikethrough: "يتوسطه خط",
    fontColor: "لون الخط",
    highlightColor: "لون تمييز النص",
    insertLink: "إدراج رابط",
    insertLinkShortcut: "إدراج رابط (Ctrl+K)",
    superscript: "كتابة مرتفعة",
    superscriptShortcut: "كتابة مرتفعة (Ctrl+Shift+=)",
    subscript: "كتابة منخفضة",
    subscriptShortcut: "كتابة منخفضة (Ctrl+=)",
    imageProperties: "خصائص الصورة",
    imagePropertiesShortcut: "خصائص الصورة (النص البديل، الحد)…",
    imageWrap: "التفاف النص",
    altText: "نص بديل",
    clearFormatting: "مسح التنسيق",
    formatPainter: "نسخ التنسيق",
    formatPainterShortcut: "نسخ التنسيق (Ctrl+Alt+C، Ctrl+Alt+V)",
    commentsAndChanges: "التعليقات والتغييرات",
    more: "المزيد",
    paragraphMarks: "إظهار علامات الفقرات",
  },
  alignment: { alignLeft: "محاذاة لليسار", center: "توسيط", alignRight: "محاذاة لليمين", justify: "ضبط" },
  lists: {
    ariaLabel: "القوائم",
    typeAriaLabel: "نوع القائمة",
    indentationAriaLabel: "مسافة البادئة",
    bulletList: "قائمة نقطية",
    numberedList: "قائمة مرقّمة",
    decreaseIndent: "إنقاص المسافة البادئة",
    increaseIndent: "زيادة المسافة البادئة",
  },
  lineSpacing: {
    label: "تباعد الأسطر",
    single: "مفرد",
    double: "مزدوج",
    lineSpacingTitle: "تباعد الأسطر: {label}",
    blockSpacingRules: "تباعد الفقرات",
    addSpaceBefore: "إضافة مسافة قبل الفقرة",
    removeSpaceBefore: "إزالة المسافة قبل الفقرة",
    addSpaceAfter: "إضافة مسافة بعد الفقرة",
    removeSpaceAfter: "إزالة المسافة بعد الفقرة",
    options: "خيارات تباعد الأسطر…",
  },
  styles: {
    selectAriaLabel: "اختيار نمط الفقرة",
    normalText: "نص عادي",
    title: "عنوان رئيسي",
    subtitle: "عنوان فرعي",
    heading1: "عنوان 1",
    heading2: "عنوان 2",
    heading3: "عنوان 3",
  },
  font: {
    selectAriaLabel: "اختيار الخط",
    sansSerif: "بدون حواف",
    serif: "بحواف",
    monospace: "ثابت العرض",
    documentFonts: "خطوط المستند",
    search: "بحث في الخطوط",
  },
  fontSize: { decrease: "تصغير الخط", increase: "تكبير الخط", label: "حجم الخط", listLabel: "أحجام الخط" },
  zoom: { ariaLabel: "التكبير: {label}", zoomOut: "تصغير", zoomIn: "تكبير", zoomLevel: "مستوى التكبير", automatic: "تلقائي", fitWidth: "ملاءمة العرض" },
  colorPicker: {
    highlightColors: "ألوان التمييز",
    customColor: "لون مخصص",
    noColor: "بلا لون",
    automatic: "تلقائي",
    themeColors: "ألوان السمة",
    standardColors: "ألوان قياسية",
    apply: "تطبيق",
    colors: {
      black: "أسود",
      darkRed: "أحمر داكن",
      red: "أحمر",
      orange: "برتقالي",
      yellow: "أصفر",
      darkYellow: "أصفر داكن",
      green: "أخضر",
      darkGreen: "أخضر داكن",
      blue: "أزرق",
      darkBlue: "أزرق داكن",
      purple: "بنفسجي",
      white: "أبيض",
      lightGreen: "أخضر فاتح",
      lightBlue: "أزرق فاتح",
      darkGray: "رمادي داكن",
      cyan: "سماوي",
      darkCyan: "سماوي داكن",
      magenta: "أرجواني",
      darkMagenta: "أرجواني داكن",
      lightGray: "رمادي فاتح",
      brightGreen: "أخضر ساطع",
    },
  },
  contextMenu: {
    ariaLabel: "القائمة السياقية",
    cut: "قص",
    copy: "نسخ",
    paste: "لصق",
    pasteWithoutFormatting: "لصق بدون تنسيق",
    copyFormatting: "نسخ التنسيق",
    pasteFormatting: "لصق التنسيق",
    delete: "حذف",
    selectAll: "تحديد الكل",
  },
  navigation: {
    ariaLabel: "التنقل في المستند",
    title: "التنقل",
    openAriaLabel: "فتح جزء التنقل",
    openTitle: "التنقل",
    closeAriaLabel: "إغلاق جزء التنقل",
    closeTitle: "إغلاق التنقل",
    tabs: { headings: "العناوين", find: "بحث" },
    headings: { noHeadings: "لا توجد عناوين. أضف عناوين للمستند لتظهر هنا." },
    find: {
      placeholder: "ابحث في المستند",
      inputAriaLabel: "ابحث في المستند",
      clearAriaLabel: "مسح البحث",
      previousAriaLabel: "النتيجة السابقة",
      nextAriaLabel: "النتيجة التالية",
      matchCase: "مطابقة حالة الأحرف",
      wholeWord: "كلمات كاملة فقط",
      optionsAriaLabel: "خيارات البحث",
      resultsAriaLabel: "نتائج البحث",
      noResults: "لا نتائج",
      searching: "جارٍ البحث…",
      counter: "النتيجة {current} من {total}",
      counterTruncated: "النتيجة {current} من {total}+",
    },
  },
  documentOutline: {
    ariaLabel: "مخطط المستند",
    closeAriaLabel: "إغلاق المخطط",
    closeTitle: "إغلاق المخطط",
    title: "المخطط",
    noHeadings: "لا توجد عناوين. أضف عناوين للمستند لتظهر هنا.",
  },
  titleBar: { untitled: "بدون عنوان", documentNameAriaLabel: "اسم المستند", menuBarAriaLabel: "شريط القوائم" },
  editingMode: {
    label: "وضع التحرير",
    editing: "تحرير",
    editingHint: "تعديل المستند مباشرة",
    suggesting: "اقتراح",
    suggestingHint: "تتحول التعديلات إلى اقتراحات",
    viewing: "عرض",
    viewingHint: "للقراءة فقط",
  },
  loading: { label: "جارٍ التحميل" },
  headerFooter: {
    chromeAriaLabel: "تحرير الرأس والتذييل",
    header: "الرأس",
    footer: "التذييل",
    firstPageHeader: "رأس الصفحة الأولى",
    firstPageFooter: "تذييل الصفحة الأولى",
    evenPageHeader: "رأس الصفحات الزوجية",
    evenPageFooter: "تذييل الصفحات الزوجية",
    sameAsPrevious: "مثل السابق",
    sameAsPreviousHint: "تنطبق التعديلات أيضاً على صفحات القسم السابق.",
    options: "خيارات",
    differentFirstPage: "صفحة أولى مختلفة",
    differentOddEven: "صفحات فردية وزوجية مختلفة",
    differentOddEvenHint: "ينطبق على المستند كله.",
    linkToPrevious: "ربط بالسابق",
    unlinkFromPrevious: "فك الربط بالسابق",
    headerDistance: "بعد الرأس عن الحافة",
    footerDistance: "بعد التذييل عن الحافة",
    removeHeader: "حذف الرأس",
    removeFooter: "حذف التذييل",
    insertPageNumber: "إدراج رقم الصفحة",
    insertTotalPages: "إدراج عدد الصفحات",
    insertSectionPages: "إدراج عدد صفحات القسم",
    insertPageXofY: "إدراج «صفحة X من Y»",
  },
  toc: { refresh: "تحديث جدول المحتويات", refreshPageNumbers: "تحديث أرقام الصفحات" },
};
